CREATE TABLE academics (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL
);
CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL
);
CREATE TABLE chores (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL
);

